model:
  class_path: modules.SHSGAN
  init_args:
    # --- Generator/Discriminator settings ---
    in_channels: 1            # e.g. RGB input (3)
    out_channels: 16          # number of HSI spectral bands
    img_size: [224, 224]      # input resolution of RGB/noise
    base_filters: 64          # base feature maps in generator U-Net
    critic_fft_arm: true      # whether Critic uses the FFT branch

    # --- Training hyperparameters ---
    lr: 0.0002
    betas: [0.5, 0.999]
    lambda_gp: 10.0           # gradient penalty coefficient
    n_critic: 5               # critic updates per generator step

    # --- Logging ---
    num_log_samples: 2        # number of samples to log each epoch
    log_channels: [0, 1, 2]   # channels used for pseudo-RGB logging

trainer:
  log_every_n_steps: 10
  max_epochs: 10

  logger:
    class_path: WandbLogger
    init_args:
      save_dir: logs
      entity: k298976-unicamp
      project: hypersynth
      tags: [hsi, gan, shs-gan]
      log_model: false

  callbacks:
    - class_path: ModelCheckpoint
      init_args:
        filename: epoch={epoch:02d}-g_loss={val/g_loss:.4f}-d_loss={val/d_loss:.4f}
        monitor: val/g_loss        
        verbose: true
        save_last: true
        mode: min
        auto_insert_metric_name: false

    - class_path: EarlyStopping
      init_args:
        monitor: val/g_loss      
        min_delta: 0.01
        patience: 15
        verbose: true
        mode: min
        strict: true

    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
